# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true 
cache: packages
branches:
    only:
        - master
        - dev
matrix:
    include:
        - os: linux
          r: release
        - os: linux
          r: oldrel 
        - os: linux
          r: devel
        - os: osx
          r: release
        - os: osx
          r: oldrel
r_packages:
    - covr
    - igraph
    - testthat
after_success:
    - Rscript -e 'covr::codecov()'

