# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true 
cache: packages
branches:
    only:
        - master
matrix:
    include:
        - os: linux
          r: release
        - os: linux
          r: oldrel 
        - os: linux
          r: devel
        - os: osx
          r: release
        - os: osx
          r: oldrel
install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install libgit2; fi
before_script:
  - Rscript -e 'install.packages(c("igraph", "testthat"))'
